name: pxc

releases:
- name: pxc
  version: latest
- name: bpm
  version: latest

instance_groups:
- name: mysql
  azs:
  - z1
  instances: 1
  jobs:
  - name: mysql
    release: pxc
  networks:
  - name: default
  persistent_disk: 10000
  properties:
    admin_password: ((admin_password))
    audit_log:
      enabled: true
    broker_admin_password: ((broker_admin_password))
    default_schema: default_schema
    enable_lower_case_table_names: false
  stemcell: default
  vm_type: default

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000

variables:
- name: admin_password
  type: password
- name: broker_admin_password
  type: password
